apiVersion: v1
appVersion: RELEASE.2019-05-14T23-57-45Z
description: MinIO is a high performance distributed object storage server, designed
  for large-scale private cloud infrastructure.
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: dev@minio.io
  name: Minio
- email: nitish@min.io
  name: nitisht
- email: sid@min.io
  name: wlan0
name: minio
sources:
- https://github.com/minio/minio
version: 2.4.16
